export const INCOMMING_PAYMENT_REQUEST = "INCOMMING_PAYMENT_REQUEST";
export const INCOMMING_PAYMENT_SUCCESS = "INCOMMING_PAYMENT_SUCCESS";
export const INCOMMING_PAYMENT_FAILURE = "INCOMMING_PAYMENT_FAILURE";
