export const INCOMMING_SERVICE_REQUEST_REQUEST = "INCOMMING_SERVICE_REQUEST_REQUEST";
export const INCOMMING_SERVICE_REQUEST_SUCCESS = "INCOMMING_SERVICE_REQUEST_SUCCESS";
export const INCOMMING_SERVICE_REQUEST_FAILURE = "INCOMMING_SERVICE_REQUEST_FAILURE";

export const USER_REQUESTED_SERVICE_REQUEST = "USER_REQUESTED_SERVICE_REQUEST";
export const USER_REQUESTED_SERVICE_SUCCESS = "USER_REQUESTED_SERVICE_SUCCESS";
export const USER_REQUESTED_SERVICE_FAILURE = "USER_REQUESTED_SERVICE_FAILURE";

export const USER_REQUESTED_SERVICE_LIST_REQUEST = "USER_REQUESTED_SERVICE_LIST_REQUEST";
export const USER_REQUESTED_SERVICE_LIST_SUCCESS = "USER_REQUESTED_SERVICE_LIST_SUCCESS";
export const USER_REQUESTED_SERVICE_LIST_FAILURE = "USER_REQUESTED_SERVICE_LIST_FAILURE";

export const APPROVE_REQUESTED_SERVICE_REQUEST = "APPROVE_REQUESTED_SERVICE_REQUEST";
export const APPROVE_REQUESTED_SERVICE_SUCCESS = "APPROVE_REQUESTED_SERVICE_SUCCESS";
export const APPROVE_REQUESTED_SERVICE_FAILURE = "APPROVE_REQUESTED_SERVICE_FAILURE";

export const VIEW_ACCEPTED_SERVICE_REQUEST = "VIEW_ACCEPTED_SERVICE_REQUEST";
export const VIEW_ACCEPTED_SERVICE_SUCCESS = "VIEW_ACCEPTED_SERVICE_SUCCESS";
export const VIEW_ACCEPTED_SERVICE_FAILURE = "VIEW_ACCEPTED_SERVICE_FAILURE";
