export const INCOMMING_SERVICE_REQUEST_REQUEST = "INCOMMING_SERVICE_REQUEST_REQUEST";
export const INCOMMING_SERVICE_REQUEST_SUCCESS = "INCOMMING_SERVICE_REQUEST_SUCCESS";
export const INCOMMING_SERVICE_REQUEST_FAILURE = "INCOMMING_SERVICE_REQUEST_FAILURE";

export const SERVICE_REQUESTED_REQUEST = "SERVICE_REQUESTED_REQUEST";
export const SERVICE_REQUESTED_SUCCESS = "SERVICE_REQUESTED_SUCCESS";
export const SERVICE_REQUESTED_FAILURE = "SERVICE_REQUESTED_FAILURE";