export const INCOMMING_SERVICE_REQUEST_REQUEST = "INCOMMING_SERVICE_REQUEST_REQUEST";
export const INCOMMING_SERVICE_REQUEST_SUCCESS = "INCOMMING_SERVICE_REQUEST_SUCCESS";
export const INCOMMING_SERVICE_REQUEST_FAILURE = "INCOMMING_SERVICE_REQUEST_FAILURE";

export const USER_REQUESTED_SERVICE_REQUEST = "USER_REQUESTED_SERVICE_REQUEST";
export const USER_REQUESTED_SERVICE_SUCCESS = "USER_REQUESTED_SERVICE_SUCCESS";
export const USER_REQUESTED_SERVICE_FAILURE = "USER_REQUESTED_SERVICE_FAILURE";

export const USER_REQUESTED_SERVICE_LIST_REQUEST = "USER_REQUESTED_SERVICE_LIST_REQUEST";
export const USER_REQUESTED_SERVICE_LIST_SUCCESS = "USER_REQUESTED_SERVICE_LIST_SUCCESS";
export const USER_REQUESTED_SERVICE_LIST_FAILURE = "USER_REQUESTED_SERVICE_LIST_FAILURE";
